### ISSUE TITLE
compiling gui

### ISSUE THREAD

**Issue by ericwa** [ericwa/ericw-tools#182]
a simple gui for running qbsp/vis/light , integrated with the tools, could be handy

**Comment by dumptruckDS** [comment]
Are you thinking about something like Necros' GUI? I would take a look at his if you haven't lately.

**Comment by ericwa** [comment]
Yeah, I was thinking something like that.
- browse button to select .map file
- browse button to select output folder
- log window for compile output
- text fields for adding command-line arguments

**Comment by PritchardGSD** [comment]
I'm guessing that this would just be another binary that's included with the releases?

**Comment by ericwa** [comment]
I was thinking another binary with the GUI that would have the qbsp/vis/light code built in. The advantage over necros's or TB's compiler GUI would be that you wouldn't need to find the qbsp.exe/vis.exe/light.exe binaries.

I dunno, on second thought maybe it's not that useful, or at least there's other stuff that would be a better use of time.
