### ISSUE TITLE
Question re: luxel projection on non-axial planes

### ISSUE THREAD

**Issue by jdolan** [ericwa/ericw-tools#210]
Hi @ericwa. First, I wanted to thank you for all of the work you've put into these tools. They're remarkable.

I wanted to ask you about how your light tool performs with non-axial planes, because we've been trying to address a very old, very ugly bug in [Quetoo](/jdolan/quetoo)'s BSP compiler, `quemap`. Here's a screenshot of the problem, with `GL_NEAREST`, maybe you're familiar with it:

<img width="1680" alt="screen shot 2018-03-21 at 10 15 16 pm" src="https://user-images.githubusercontent.com/643118/37769945-2453bbe8-2da9-11e8-8327-25e1d5688be2.png">

Additional shots with trilinear filtering, perhaps more familiar looking if you've seen this in-game:
<img width="1680" alt="screen shot 2018-03-22 at 8 38 02 am" src="https://user-images.githubusercontent.com/643118/37770966-7d429fdc-2dac-11e8-9ae3-21473975ac6b.png">
<img width="1680" alt="screen shot 2018-03-22 at 8 38 06 am" src="https://user-images.githubusercontent.com/643118/37770972-80604340-2dac-11e8-9e06-bdc8ad3b092e.png">

Those arches in the corner appear to stretch or skew the light source's projection, and we end up with horrible artifacts. Phong shading (not enabled there) helps to mask the problem somewhat, but there's clearly something fundamentally wrong.

Our working theory is that the code that generates the world space points for each luxel is flawed or insufficient for non-axial planes. The original Quake2 tools, which `quemap` is based on, have some real gnarly math in them to resolve the first luxel coordinate, and a pair of texture vectors, in world space. I'm sure you're familiar with it:

Stock tools: https://github.com/id-Software/Quake-2-Tools/blob/master/bsp/qrad3/lightmap.c#L562
And here in Quemap: https://github.com/jdolan/quetoo/blob/master/src/tools/quemap/lightmap.c#L151

I started to poke at the this code, and step through it, and I found that the faces where things go wrong all have one thing in common: the `scale` variable was not `1.0`. I started to play with the projection of the luxel origin point back onto the surface plane, and I found that I was able to influence these artifacts, but not remove them.

Then I looked at your tools, and saw you're using a 4x4 matrix for this. I figured you'd solved it. I was so excited. So last night, I went and ported that matrix to `quemap`:

https://github.com/jdolan/quetoo/blob/lightmap-texture-arrays/src/tools/quemap/lightmap.c#L95

But sadly, the screenshot above was actually generated using the texture matrix I've borrowed from your tools. It produces the same exact artifacts.

So, my very long-winded question to you is: do you know if these light artifacts manifest in your tools? Do you know what might be going wrong with these calculations?

Attached is a very simple .map I've been using to try to debug this.
[lighttest.zip](https://github.com/ericwa/ericw-tools/files/1837498/lighttest.zip)

If you've fixed this, I'd love it if you could point me in the right direction. If your tools still exhibit this bug, I'd like to work together with you to try to resolve it for both tools.

**Comment by ericwa** [comment]
Hey @jdolan - interesting problem!

A quick & dirty visual way I debug sample point positioning is dump the world positions to a .map file using a point entity for each sample point, then load them a map editor and paste into the original map.
https://github.com/ericwa/ericw-tools/blob/master/light/ltface.cc#L549

One thing I would check is the distance off the face plane. In my tools I think I use the 4x4 matrix to convert to world space, but then I project the points back on to the face plane and lift them off again by 1 world space unit.

I can have a look later today and try your test case with my tools.

**Comment by ericwa** [comment]
Hey @jdolan .. finally tested this. I modified the map a bit to be quake 1 format and test phong shading as well:
[lighttest-quake.map.zip](https://github.com/ericwa/ericw-tools/files/1911451/lighttest-quake.map.zip)

Coarse slope: (left has phong shading, right doesn't)
![spasm0053](https://user-images.githubusercontent.com/239161/38773446-c1ddf35c-4009-11e8-9c5d-ce87ee8fcae6.png)

Fine slope: (left has phong shading, right doesn't)
![spasm0054](https://user-images.githubusercontent.com/239161/38773448-c63d4286-4009-11e8-9b64-bda7107971b9.png)

I think the "banding" pattern that is visible on right right (non-phong-shaded) slopes is expected due to the cosine law.. so there might not actually be a bug in your code, not sure.

Phong shading should eliminate this banding and my implementation does, mostly. I didn't use `-extra4` (4x oversampling) which would make it a bit smoother.

**Comment by ericwa** [comment]
Edit: turning up the light intensity, I can get the sawtooth pattern to look more pronounced like your screenshot:
![spasm0058](https://user-images.githubusercontent.com/239161/38773564-f741aa72-400c-11e8-87a5-1014f58ab257.png)
![spasm0057](https://user-images.githubusercontent.com/239161/38773567-0378753c-400d-11e8-9c12-aa3411382f44.png)
 
[lighttest-quake2.map.zip](https://github.com/ericwa/ericw-tools/files/1911470/lighttest-quake2.map.zip)
