### ISSUE TITLE
In some cases ray.mask can't store all ray indices. 

### ISSUE THREAD

**Issue by m-x-d** [ericwa/ericw-tools#220]
https://github.com/ericwa/ericw-tools/blob/80dc99ebee5110691795aef261fa7c05e9ddc789/light/trace_embree.cc#L696

When using -extra4 + _lightmap_scale 1 a 128x128 surface will use 262144 rays while only 32766 can be stored in ray.mask

**Comment by ericwa** [comment]
Hmm, it looks like the 16 bits of RAYMASK_MODELINDEX_MASK can be reduced to 1 bit, because it's only used to tell if the surface whose lighting is being calculated is part of the world or not. That would free up more room in the mask for the rays indices.

**Comment by ericwa** [comment]
Fixed in 4456020b30262a71ea04789ccf61074350e432bf
