### ISSUE TITLE
Empty .map crashes qbsp

### ISSUE THREAD

**Issue by hrehfeld** [ericwa/ericw-tools#229]
## version
`qbsp / ericw-tools v0.18.1-15-gfc72bbb`

## cmdline
`qbsp -nopercent -nofill -noverbose /home/hrehfeld/.quakespasm/id1/maps/prefab/wmet4_8-wall0-fgd.map /home/hrehfeld/.quakespasm/id1/maps/prefab/wmet4_8-wall0-fgd.bsp
`
## .map
```
// Game: Quake
// Format: Standard
{
"classname" "worldspawn"
"_sun_mangle" "60 -45 0"
"wad" "../wad/QUAKE101.WAD;../wad/newskip.wad"
"_sunlight" "300"
}

```

## crash
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

```

**Comment by ericwa** [comment]
Fixed in >=2.0.0-alpha1
