### ISSUE TITLE
HOM's

### ISSUE THREAD

**Issue by whirledtsar** [ericwa/ericw-tools#239]
As explained on func_msgboard, seemingly normal, random areas become HOM's ingame. Enclosed is the .map file (plus texture wads), with irrelevant brushes cut out. After compiling, walk forward to enter one HOM zone or look backwards to see another.

Edit: OK, my bad, I've found out that one of the HOM's was related to engine limits of map coordinates. But the other one is unrelated, still an enigma. Here's a better file, with all irrelevant geometry/textures cut out, just start the map to see the problem.

https://www.mediafire.com/file/jgdj2wdkvxd2pih/map.zip/file

**Comment by whirledtsar** [comment]
Updated with new information and better example map/bsp file.

**Comment by ericwa** [comment]
Can't reproduce in uhexen2 (other than by walking backwards so the player position wraps around). Which engine (gl or software) had the homs?

**Comment by whirledtsar** [comment]
I just checked and it apparently only occurs in the GL engine. So I assume
it's not an issue with the compilers. Sorry for bothering you.

**Comment by ericwa** [comment]
No prob, thanks for checking!
