### ISSUE TITLE
Light Fails on MAC for Missing Embree 2.xx Package libembree.2.dylib

### ISSUE THREAD

**Issue by JosiahJack** [ericwa/ericw-tools#243]
As found by Albert on Discord:
"As far as I can tell, I get ...1 error:
Errors
#### Executing '/QuakeDev/tools/ericwtools/bin/light -threads 1 firstmap.bsp'
dyld: Library not loaded: @rpath/libembree.2.dylib
  Referenced from: /QuakeDev/tools/ericwtools/bin/light
  Reason: image not found
#### Finished with exit status -5"

Using Mac Darwin build.  It appears he is missing the required Intel Embree 2.xx package for raytracing.

**Comment by ericwa** [comment]
Turns out to be, the embree dylib doesn't support macos 10.9. For now we're stuck with embree although I wanted to restore the built-in bsp raytracing at some point.
