### ISSUE TITLE
In some cases fix_coord can return invalid coordinates

### ISSUE THREAD

**Issue by m-x-d** [ericwa/ericw-tools#260]
https://github.com/ericwa/ericw-tools/blob/d53c298bd8522337efc3c5760c02f2c528fe991b/light/trace.cc#L288

The logic and usage implies that fix_coord should return result in [0 .. width-1] range, but in some cases this isn't true.
For example, fix_coord(-128, 128) and fix_coord(0, 128) will return 128.

My fix:
```javascript
static uint32_t fix_coord(vec_t in, uint32_t width)
{
    int32_t result = (int32_t)in % width;
    return (uint32_t)(result < 0 ? result + width : result);
}
```

**Comment by ericwa** [comment]
Thanks for the catch! I applied a slightly different fix because I wanted `clamp_texcoord(-0.5f, 128)` to be 127, and added some test cases.
