### ISSUE TITLE
Mangle on _sun interpreted as a vector

### ISSUE THREAD

**Issue by ericwa** [ericwa/ericw-tools#266]
Instead of as a mangle

**Comment by hemebond** [comment]
@ericwa Is this what causes mangle to be ignored on `_sun` light entities, causing it to default to `0 0 0` for a horizontal sun direction?
![image](https://github.com/ericwa/ericw-tools/assets/424218/90db827d-db46-4146-8c29-be028a7b0cde)

**Comment by ericwa** [comment]
Yes,  I confirmed this is still broken on 2.0.0-alpha7.

The intended behaviour is that `"mangle"` works like it does on a spotlight (e.g. so you can use the TB arrow as a guide).

Should be a quick fix, looking into it.
