### ISSUE TITLE
Add _phong option to Worldspawn

### ISSUE THREAD

**Issue by bstordeur** [ericwa/ericw-tools#267]
Having _phong available in Worldspawn would be very handy in maps where you want most stuff to be phonged, instead of having to apply it all the time to your brushes.

**Comment by Lain-tf** [comment]
Seconding this, it's come up in several of my maps. Making giant func_group piles just to use phong on everything sucks. It looks so much better!

**Comment by ericwa** [comment]
`_phong` works on worldspawn now
