### ISSUE TITLE
Leaf portal warnings in 0.18.2-rc1

### ISSUE THREAD

**Issue by Poorchop** [ericwa/ericw-tools#274]
Compiling a map with 0.18.2-rc1, I always get the following:
```
WARNING: Leaf portals saw into leaf (x)
```
where x is a number that increases with the number of these warnings. The warning itself increases in number as map complexity increases. This warning does not occur with 0.18.1.

Tested in Windows 10 x64.

**Comment by ericwa** [comment]
Yeah, I saw this as well. It was caused when I fixed: https://github.com/ericwa/ericw-tools/issues/261

As far as I can tell the warning is harmless, but I will have a closer look at some point.

**Comment by ericwa** [comment]
The warning was a hint about https://github.com/ericwa/ericw-tools/issues/263

This is fixed in 2.0.0-alpha4

**Comment by Poorchop** [comment]
Thanks for all of your work.
