### ISSUE TITLE
Hint / skip brush logic error

### ISSUE THREAD

**Issue by jdolan** [ericwa/ericw-tools#303]
https://github.com/ericwa/ericw-tools/blob/6f99f469c6c2b3bdddc88d89368cabb1a7054ec8/qbsp3/map.cc#L641

This line toggles the detail bit on the _surface_ flags, not the contents flags. And the contents flags were cleared in the line above, so really, this line should just be removed.

**Comment by ericwa** [comment]
this was in a mirrored copy of qbsp3 but not the actual ericw-tools codebase
