### ISSUE TITLE
Add textures export when textures can't be found and notex is enabled

### ISSUE THREAD

**Issue by rmn20** [ericwa/ericw-tools#304]
I want to load png textures from folders in my engine using texture names from bsp, but qbsp never exports texture names that it cannot load, even if notex is enabled.

**Comment by rmn20** [comment]
Maybe I should use the Quake 2 map format instead? But it looks like qbsp still can't load png files(trenchbroom uses them). I checked the source code and it looks like the compiler can only load wal, pcx and tga...

**Comment by ericwa** [comment]
Sorry, long overdue reply..

Yes, q2bsp would be best for this, we added png loading some time before `2.0.0-alpha1` as well.

For q1bsp, 2.0.0-alpha5 adds `-missing_textures_as_zero_size` which is like `-notex` but it will make qbsp write the size as 0x0, along with the name, if it can't find the texture. (with just `-notex`, if the texture can't be loaded by qbsp, we omit both the name and the size)
