### ISSUE TITLE
Levels with names such as "2hrsm" fail to compile lighting. 

### ISSUE THREAD

**Issue by Lain-tf** [ericwa/ericw-tools#307]
This seems to be a problem with using "2" at the start of your filename.
This has only been tested with Windows 10 machines.

**Comment by onetruepurple** [comment]
@ericwa Is this maybe a shadow of the old computing "variables beginning with numbers" problem?

**Comment by ericwa** [comment]
Not sure what was going on here. This is producing a properly lit bsp with `ericw-tools-v0.18.1-32-g6660c5f-win64` as well as current dev:

```
qbsp.exe 2hrsm.map
light.exe 2hrsm.map
```
