### ISSUE TITLE
Cordon feature in qbsp

### ISSUE THREAD

**Issue by ericwa** [ericwa/ericw-tools#311]
Delete any brushes not inside a "cordon" textured brush?

**Comment by bstordeur** [comment]
This would be neat, you'd still have to seal it somehow ideally though if you wanted precision lighting, but I guess even without sealing it would be a good to have!

**Comment by 4LT** [comment]
"Invert" the cordon brush and texture it "skip" on export?

**Comment by ericwa** [comment]
Implemented in 39a54abfc6ef87e753383d2e46a1d4ed59c0eb97 + bd047020d2f7306d8a341995caf943f69e9e2bbf (use a brush with texture name "region".) There's also "antiregion" which is like a solid brush but deletes point entities inside.
