### ISSUE TITLE
Horizontal train with origin brush z-axis translation issue.

### ISSUE THREAD

**Issue by Jaypers** [ericwa/ericw-tools#323]
**Environment Details**
**_Tool version:_** ericw-tools-v0.18.1-win64
**_Engine:_**         Quakespasm 0.94.1_win64
**_Map editor:_**  Trenchbroom 2021.1

**Problem**
I've created a horizontal train (with origin brush) that travels across a +/- 4096 map parallel to the y-axis. (see map and bsp files attached)

When changing the width of the train it affects its z-axis orientation even after re-centering the origin brush.

Note: I've tried setting `_no_bbox_rotation_expansion` to `1` but made no difference...
Not sure this option is still available in ericw-tools anymore or if it would even solve the problem?

Any details about why the z coords are affected by the increased width of the train would be helpful.

[train_origin_brush.zip](https://github.com/ericwa/ericw-tools/files/7189806/train_origin_brush.zip)

**Comment by Jaypers** [comment]
![image](https://user-images.githubusercontent.com/39566161/133887640-15953a44-9ec7-4950-9bf8-e84e550220ae.png)

**Comment by Jaypers** [comment]
![image](https://user-images.githubusercontent.com/39566161/133887757-a38f22b2-7999-4341-bf72-a3c997569ffb.png)

**Comment by Jaypers** [comment]
![image](https://user-images.githubusercontent.com/39566161/133887864-e7e9ace3-0efe-4b88-84d5-79748eeb3beb.png)

**Comment by ericwa** [comment]
Here's what I get with the current code:
![spasm0032](https://user-images.githubusercontent.com/239161/133896221-a4ad77b9-bf7c-4a30-aff3-6a2072c5a9e1.png)

Screenshot from quakespasm with `r_drawflat 1` and `r_showtris 1`.

Does that look right? I'm not sure how the gamecode is supposed to react when there's an origin brush. I think func_train always looks at the submodel's mins/maxs. IIRC in ericw-tools-v0.18.1-win64, the model mins/maxs of models with origin brushes were being "tweaked" with the assumption that the model was going to be used with Hipnotic rotation. The bounds expansion was meant to avoid models flickering out of the PVS in game when rotated.

Now, I've removed this hack when "origin" brushes are used, and only do the bounds expansion when an actual Hiprotate setup is used (info_rotate entity, etc)

Here's a build snapshot of the current code:
https://ci.appveyor.com/api/buildjobs/dwx189n8k7f3at40/artifacts/cmakebuild%2Fericw-tools-v0.18.1-200-g28b4ec7-win64.zip

**Comment by Jaypers** [comment]
I've tested with that build and yes! That looks a lot better! 

Thank you so much for the information, and the prompt response. 
Getting into Quake modding at this time is challenging so I'm really grateful!
