### ISSUE TITLE
wad field isn't found with no brushes into worldspawn 

### ISSUE THREAD

**Issue by fabiolimamp** [ericwa/ericw-tools#332]
qbsp gives out the warning "No wad or _wad key exists in the worldmodel" when there are no brushes directly inside the worldspawn entity, thus rendering the map faces completely black.

That happens in Trenchbroom under two situations at least:
- when you have no structural brushes, or when all brushes belong to some brush entity. You can reproduce that easily by creating a brush into a new map and turning it into a func_group.
- when you have no structural brushes inside the "Default layer". Trenchbroom manages layers by creating special func_groups internally, so once you have a worldspawn brush within another map layer, technically it's inside a func_group, thus falling into the same situation as above. This can be reproduced by creating a new map layer in a new map, and building a structural brush inside that layer.

Important to note that this appears to be a somewhat recent issue, not happening in the latest official release for example, nor in some other dev builds. I wasn't able to track down when exactly it appeared though.

**Comment by Paril** [comment]
This should be fixed in since #521daad432b683abc2101ac25c1231ec031c95a7 earlier today; can you confirm?

**Comment by fabiolimamp** [comment]
That fixed it yeah, thanks

**Comment by Paril** [comment]
leaving this open to remind me to fix the relative WAD options though. Atm wads are only searched in two places:
- the raw path itself, if absolute
- relative to the current working directory (.exe path generally, but not sure if TB sets working dir alongside the .map)

for completeness I should also have it check alongside the .map if the other two fail. I think that's what the old tools did.

**Comment by ericwa** [comment]
I think I got that implemented:
https://github.com/ericwa/ericw-tools/commit/e05a2bdf750f65b6a15f13fbfb1141755303300d#diff-a80b14c14661c01eb1e3416d5792c8b178b963bf017b1e378f951f4e64f8f427L701

**Comment by Paril** [comment]
oh no I mean wad loading relative to the .map file - or wrong commit?

**Comment by ericwa** [comment]
That commit updated `gamedef_q1_like_t::init_filesystem` to add the parent dir of the map or bsp being processed to the filesystem search path. I needed that so `-add something.map` could search for a `something.map` in the same dir as the map being compiled.

It looks like .wad's use a separate search path, but we already add the parent dir of the map file to the wad search path in `qbsp_settings::postinitialize` (at least, we do if no other wad path is specified):

```
 /* If no wadpath given, default to the map directory */
    if (wadpaths.pathsValue().empty()) {
        wadpath wp{qbsp_options.map_path.parent_path(), false};

        // If options.map_path is a relative path, StrippedFilename will return the empty string.
        // In that case, don't add it as a wad path.
        if (!wp.path.empty()) {
            wadpaths.addPath(wp);
        }
    }
```

**Comment by Paril** [comment]
oh I see, I missed this. should be good then I think?
