### ISSUE TITLE
func_detail_wall doesn't generate wrbrushes

### ISSUE THREAD

**Issue by Igameart** [ericwa/ericw-tools#363]
This may also extend to func_detail and func_detail_illusionary.

Func_wall clip
![image](https://github.com/ericwa/ericw-tools/assets/5240715/a1800c4c-81fa-44ec-80a4-1169dd8ca90f)

Func_detail_wall clip (absent)
![image](https://github.com/ericwa/ericw-tools/assets/5240715/bdd23924-6729-4e1c-9231-5ba370299a7b)

**Comment by ericwa** [comment]
Fixed in 2b22e3566916892eca7208589527be728f47186b + be8ae00fa6fb6057d0acb506a6cd6a15b9b2cf3d
