### ISSUE TITLE
Styled lights dont work In Quake 2

### ISSUE THREAD

**Issue by JafiMapping** [ericwa/ericw-tools#381]
Styled lights dont work In quake 2. Even if assign lights style number, like flicker, candle, pulse, they show static in the game. Any ideas?

**Comment by Paril** [comment]
This was a bug in the 2.0.0 pre release - leaked maps remove all style keys. Seal the map or check appveyor/actions to get an updated binary.

**Comment by ericwa** [comment]
Should be fixed in alpha2: https://github.com/ericwa/ericw-tools/releases/tag/2.0.0-alpha2

**Comment by JafiMapping** [comment]
Ok that was it .. I had a hole.  The light compile was longer too, i should have  suspect something.  Im new  these tools, i was working with Qbism Q2 tools, 220 which it was a bit clearer when have a hole. Ill give a try with the alpha 2. Thank you!
