### ISSUE TITLE
Switchable lights (start off) cast false light on 1st map load

### ISSUE THREAD

**Issue by Return2Perdition** [ericwa/ericw-tools#383]
On 1st map load, switchable lights (start off) cast false light.
If you reload the map, the light will be correct.

[https://drive.google.com/drive/folders/1ZoCOGdmDT29AVlhwlZOLRLucwt0gHRiI?usp=sharing](url)

map:
[https://drive.google.com/file/d/1dEr-NEq_PXP7pE4AOY8oSsQ-RwOxxOEG/view?usp=sharing](url)

**Comment by Paril** [comment]
Switchables are handled entirely by the game; there's no way for the tool to do something like this (conditionally making lights darker only on the first launch). Chances are your mods' game DLL is handling them improperly or something.

**Comment by Return2Perdition** [comment]
Thanks, i found a bug in the KMQuake2 menue.
