### ISSUE TITLE
31 character texture name length limitation relative to basedir, anything beyond that is silently discarded

### ISSUE THREAD

**Issue by starfrost013** [ericwa/ericw-tools#396]
I am working on a quake 2 engine based game and this is not even indicated in a warning message, it would be nice to overload it with a command-line option or something.

**Comment by MissLavender-LQ** [comment]
how r u gettint wads with textures above 31char

**Comment by starfrost013** [comment]
i'm not using wads???? it's quake 2 based???

**Comment by MissLavender-LQ** [comment]
agh i keep forgetting tho i think u can still use wads with q2

**Comment by Paril** [comment]
Yeah unfortunately this isn't fixable without a secondary BSPX lump or something, and even then you'd still need modified engine support.

If you make an alternate BSP38-based format with longer filenames we can potentially add support for it.

**Comment by ericwa** [comment]
The warning is working in alpha4, it prints near the end of the `qbsp` output in the `EmitFaces` section:

![image](https://github.com/ericwa/ericw-tools/assets/239161/ed16bdde-2584-4620-9494-ea00adb68ca3)

This is running on the `q2_long_texture_name.map` testmap like this:
`qbsp.exe -q2bsp -basedir .\q2_wal_metadata\ .\q2_long_texture_name.map`
