### ISSUE TITLE
relative lip requirements

### ISSUE THREAD

**Issue by victorbstan** [ericwa/ericw-tools#410]
I'm trying to run the Darwin version of the built executables (latest prerelease) and it seems to require that the libs be in `/usr/lib/`, is there a way to make the libs required relative to the executable, they seem to be there in the downloaded package. 
```
/Users/victor/Downloads/ericw-tools-2.0.0-alpha5-Darwin/bin/maputil
  Reason: tried: '/usr/local/lib/libtbb.12.dylib' (no such file), '/usr/lib/libtbb.12.dylib' (no such file, not in dyld cache)
```

**Comment by ericwa** [comment]
IIRC the mac builds are broken in alpha1 through alpha5, but they'll be fixed in alpha 6 when it's released, I set up the rpath stuff correctly in this commit:

39074b8249de8670b3cdf09673ac71412f36529c
