### ISSUE TITLE
[BUG] Buggy collision with clip brushes inside an entity.

### ISSUE THREAD

**Issue by Zungrysoft** [ericwa/ericw-tools#438]
To reproduce, create a func_wall or func_door composed of both a clip brush and a non-clip brush. Jump or walk into that clip brush. You will get stuck on it instead of smoothly sliding off of it like other walls.

I have tested this with both FTEQW and Ironwail.

I have encountered this bug on the current latest version `2.0.0-alpha8`. The latest version I've used that did not have this bug is `0.18.2-rc1`.

**Comment by ericwa** [comment]
Thanks, can repro it.
