### ISSUE TITLE
func_illusionary_visblocker doesn't work?

### ISSUE THREAD

**Issue by nathnolt** [ericwa/ericw-tools#440]
According to the docs, func_illusionary_visblocker should work as follows: (not be solid and block the visibility from the inside). 
But when testing with 0.18.3-rc1 or with 2.0.0-alpha8, it's solid.

When I test with v0.18.1, it works as I expect it.

Maybe the behaviour changed? or maybe there's a flag I need to add on the entity to make it work?

Map attached as .zip
[func_illusionary_visblocker-test-map.zip](https://github.com/user-attachments/files/17792108/func_illusionary_visblocker-test-map.zip)

Thanks

**Comment by ericwa** [comment]
Thanks, will try and fix this as soon as I get a chance
